from Code.DataStructures.PrimeCurves import P192, P384
from Code.PerformanceComparison.scalar_mul import ScalarMuliplicationPerformanceTest


scalar_mul_affine_test192 = ScalarMuliplicationPerformanceTest(1000, P192, [2**5, 2**32], 3)
scalar_mul_affine_test192Big = ScalarMuliplicationPerformanceTest(1000, P192, [2**128, 2**192], 3)
scalar_mul_jacobi_test192 = ScalarMuliplicationPerformanceTest(1000, P192, [2**5, 2**32], 3, jacobi=True)

scalar_mul_jacobi_test192Big_3 = ScalarMuliplicationPerformanceTest(1000, P192, [2**128, 2**192], 3, jacobi=True)
scalar_mul_jacobi_test192Big_4 = ScalarMuliplicationPerformanceTest(1000, P192, [2**128, 2**192], 4, jacobi=True)
scalar_mul_jacobi_test192Big_5 = ScalarMuliplicationPerformanceTest(1000, P192, [2**128, 2**192], 5, jacobi=True)
scalar_mul_jacobi_test192Big_7 = ScalarMuliplicationPerformanceTest(1000, P192, [2**128, 2**192], 7, jacobi=True)

scalar_mul_affine_test384 = ScalarMuliplicationPerformanceTest(1000, P384, [2**5, 2**32], 3)
scalar_mul_affine_test384Big = ScalarMuliplicationPerformanceTest(1000, P384, [2**330, 2**384], 3)
scalar_mul_jacobi_test384 = ScalarMuliplicationPerformanceTest(1000, P384, [2**5, 2**32], 3, jacobi=True)

scalar_mul_jacobi_test384Big_3 = ScalarMuliplicationPerformanceTest(1000, P384, [2**330, 2**384], 3, jacobi=True)
scalar_mul_jacobi_test384Big_4 = ScalarMuliplicationPerformanceTest(1000, P384, [2**330, 2**384], 4, jacobi=True)
scalar_mul_jacobi_test384Big_5 = ScalarMuliplicationPerformanceTest(1000, P384, [2**330, 2**384], 5, jacobi=True)
scalar_mul_jacobi_test384Big_7 = ScalarMuliplicationPerformanceTest(1000, P384, [2**330, 2**384], 7, jacobi=True)

print("SCALAR MUL")

print("*** 192 ***")
print("Binary algo")
print("Affine")
print(scalar_mul_affine_test192.binary_scalar_mul_test())
print(scalar_mul_affine_test192Big.binary_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test192.binary_scalar_mul_test())
print(scalar_mul_jacobi_test192Big_3.binary_scalar_mul_test())

print("left to right, signed")
print("Affine")
print(scalar_mul_affine_test192.left_to_right_scalar_mul_test())
print(scalar_mul_affine_test192Big.left_to_right_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test192.left_to_right_scalar_mul_test())
print(scalar_mul_jacobi_test192Big_3.left_to_right_scalar_mul_test())
print("right to left, signed")
print("Affine")
print(scalar_mul_affine_test192.right_to_left_scalar_mul_test())
print(scalar_mul_affine_test192Big.right_to_left_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test192.right_to_left_scalar_mul_test())
print(scalar_mul_jacobi_test192Big_3.right_to_left_scalar_mul_test())

print("window NAF")
print("Affine")
print(scalar_mul_affine_test192.window_naf_mul_test())
print(scalar_mul_affine_test192Big.window_naf_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test192.window_naf_mul_test())
print(scalar_mul_jacobi_test192Big_3.window_naf_mul_test())

print("Window tests, ignore for averages")
print(scalar_mul_jacobi_test192Big_3.window_naf_mul_test())
print(scalar_mul_jacobi_test192Big_4.window_naf_mul_test())
print(scalar_mul_jacobi_test192Big_5.window_naf_mul_test())

print("window NAF right to left")
print("Affine")
print(scalar_mul_affine_test192.right_to_left_scalar_mul_test())
print(scalar_mul_affine_test192Big.right_to_left_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test192.window_naf_right_to_left_test())
print(scalar_mul_jacobi_test192Big_3.window_naf_right_to_left_test())

print("Igonore for averages")
print(scalar_mul_jacobi_test192Big_3.window_naf_right_to_left_test())
print(scalar_mul_jacobi_test192Big_4.window_naf_right_to_left_test())
print(scalar_mul_jacobi_test192Big_5.window_naf_right_to_left_test())

print("sliding window")
print(scalar_mul_affine_test192.sliding_window_left_to_right_test())
print(scalar_mul_affine_test192Big.sliding_window_left_to_right_test())
print("Jacobi")
print(scalar_mul_jacobi_test192.sliding_window_left_to_right_test())
print(scalar_mul_jacobi_test192Big_7.sliding_window_left_to_right_test())

print("Ignore for averages")
print(scalar_mul_jacobi_test192Big_3.sliding_window_left_to_right_test())
print(scalar_mul_jacobi_test192Big_4.sliding_window_left_to_right_test())
print(scalar_mul_jacobi_test192Big_7.sliding_window_left_to_right_test())
print("****")



print("*** 384 ***")
print("Binary algo")
print("Affine")
print(scalar_mul_affine_test384.binary_scalar_mul_test())
print(scalar_mul_affine_test384Big.binary_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test384.binary_scalar_mul_test())
print(scalar_mul_jacobi_test384Big_3.binary_scalar_mul_test())

print("left to right, signed")
print("Affine")
print(scalar_mul_affine_test384.left_to_right_scalar_mul_test())
print(scalar_mul_affine_test384Big.left_to_right_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test384.left_to_right_scalar_mul_test())
print(scalar_mul_jacobi_test384Big_3.left_to_right_scalar_mul_test())
print("right to left, signed")
print("Affine")
print(scalar_mul_affine_test384.right_to_left_scalar_mul_test())
print(scalar_mul_affine_test384Big.right_to_left_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test384.right_to_left_scalar_mul_test())
print(scalar_mul_jacobi_test384Big_3.right_to_left_scalar_mul_test())

print("window NAF")
print("Affine")
print(scalar_mul_affine_test384.window_naf_mul_test())
print(scalar_mul_affine_test384Big.window_naf_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test384.window_naf_mul_test())
print(scalar_mul_jacobi_test384Big_3.window_naf_mul_test())

print("Window tests, ignore for averages")
print(scalar_mul_jacobi_test384Big_3.window_naf_mul_test())
print(scalar_mul_jacobi_test384Big_4.window_naf_mul_test())
print(scalar_mul_jacobi_test384Big_5.window_naf_mul_test())

print("window NAF right to left")
print("Affine")
print(scalar_mul_affine_test384.right_to_left_scalar_mul_test())
print(scalar_mul_affine_test384Big.right_to_left_scalar_mul_test())
print("Jacobi")
print(scalar_mul_jacobi_test384.window_naf_right_to_left_test())
print(scalar_mul_jacobi_test384Big_3.window_naf_right_to_left_test())

print("Igonore for averages")
print(scalar_mul_jacobi_test384Big_3.window_naf_right_to_left_test())
print(scalar_mul_jacobi_test384Big_4.window_naf_right_to_left_test())
print(scalar_mul_jacobi_test384Big_5.window_naf_right_to_left_test())

print("sliding window")
print(scalar_mul_affine_test384.sliding_window_left_to_right_test())
print(scalar_mul_affine_test384Big.sliding_window_left_to_right_test())
print("Jacobi")
print(scalar_mul_jacobi_test384.sliding_window_left_to_right_test())
print(scalar_mul_jacobi_test384Big_7.sliding_window_left_to_right_test())

print("Ignore for averages")
print(scalar_mul_jacobi_test384Big_3.sliding_window_left_to_right_test())
print(scalar_mul_jacobi_test384Big_4.sliding_window_left_to_right_test())
print(scalar_mul_jacobi_test384Big_7.sliding_window_left_to_right_test())
print("****")
